apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: demo-danweb

images:
- name: williambr2022/demo-agenda-front
  newName: williambr2022/demo-agenda-front
  newTag: afaeaf96014db14fc7b40516e8da25a9933fdd5c
